export const WORKOUTS: Workout[] = [
  {
    name: "Chest Workout",
    workouts: [
      "Bench Press",
      "Smith Machine Bench Press",
      "Incline Bench Press",
      "Smith Machine Incline Bench Press",
      "Dumbbell Bench Press",
      "Dumbbell Incline Bench Press",
      "Chest Press",
      "Machine Chest Fly",
      "Cable Fly",
      "Push Ups",
    ],
  },
  {
    name: "Back Workout",
    workouts: [
      "Pull Ups",
      "Lat Pulldown",
      "Bent Over Row",
      "Seated Cable Row",
      "Machine Reverse Fly",
      "Dumbbel Row",
      "Chin Ups",
      "T Bar Row",
      "T Machine Row",
      "Back Extension",
    ],
  },
  {
    name: "Legs Workout",
    workouts: [
      "Squat",
      "Sled Leg Press",
      "Hip Thrust",
      "Horizontal Leg Press",
      "Leg Extension",
      "Seated Leg Curl",
      "Lying Leg Curl",
      "Dumbbell Lunge",
      "Deadlift",
    ],
  },
  {
    name: "Shoulder Workout",
    workouts: [
      "Shoulder Press",
      "Dumbbell Shoulder Press",
      "Dumbbell Lateral Raise",
      "Cable Lateral Raise",
      "Dumbbell Front Raise",
    ],
  },
  {
    name: "Arm Workout",
    workouts: [
      "Dumbbell Curl",
      "Barbell Curl",
      "Hammer Curl",
      "Dips",
      "Tricep Pushdown",
      "Tricep Rope Pushdown",
      "Seated Dip Machine",
    ],
  },
  {
    name: "Core Workout",
    workouts: [
      "Sit Ups",
      "Cable Crunch",
      "Machine Seated Crunch",
      "Crunches",
      "Dumbbell Side Bend",
      "Hanging Leg Raise",
      "Russian Twist",
      "Ab Wheel Rollout",
      "Jumping Jack",
    ],
  },
];
